version: "3.7"

networks:
  mikrotik-lite-api:

services:
  redis:
      image: bitnami/redis:latest
      ports:
      - "6379:6379"
      environment:
        - ALLOW_EMPTY_PASSWORD=yes
      networks:
        - mikrotik-lite-api